name: RandomRespawn
version: 1.0
main: freegamerdev.randomrespawn.RandomRespawn
api-version: 1.19
authors: [ FreeGamer ]
description: A simple Plugin that makes Players always randomly respawn in the world withing a configurable area.
