name: RandomRespawn
version: '${project.version}'
main: freegamerdev.randomrespawn.RandomRespawn
api-version: 1.19
authors: [ FreeGamer ]
description: A simple Plugin that makes Players always randomly respawn in the world withing a configurable area.
commands:
  fly:
    description: Toggles flying for the user.
    usage: /fly
    aliases: f
    # permission: fly
    # permission-message: You do not have the permissions necessary to run this command.
